/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1rP2h5qw8a8
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function CoinPage() {
  return (
    <div className="p-6 max-w-6xl">
      <Card>
        <CardHeader className="pb-4">
          <CardTitle>Cryptocurrency Prices</CardTitle>
          <CardDescription>Open and free to download, powered by DEXes Uniswap, dydx, ...</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[280px]">Cryptocurrency</TableHead>
                  <TableHead className="w-[120px] text-right">Price</TableHead>
                  <TableHead className="w-[200px] text-right">Market Cap</TableHead>
                  <TableHead className="w-[150px] text-right">Price Change</TableHead>
                  <TableHead className="w-[150px] text-right">Price Change</TableHead>
                  <TableHead className="w-[150px] text-right">Price Change</TableHead>
                  <TableHead className="w-[150px] text-right">Price Change</TableHead>
                  <TableHead className="w-[150px] text-right">Price Change</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">Bitcoin (BTC)</TableCell>
                  <TableCell className="text-right">$45,000.00</TableCell>
                  <TableCell className="text-right">$840 Billion</TableCell>
                  <TableCell className="text-right text-green-500">+2.5%</TableCell>
                </TableRow>                <TableRow>
                  <TableCell className="font-medium">Ethereum (ETH)</TableCell>
                  <TableCell className="text-right">$3,000.00</TableCell>
                  <TableCell className="text-right">$350 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-1.3%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Binance Coin (BNB)</TableCell>
                  <TableCell className="text-right">$500.00</TableCell>
                  <TableCell className="text-right">$75 Billion</TableCell>
                  <TableCell className="text-right text-green-500">+0.7%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Tether (USDT)</TableCell>
                  <TableCell className="text-right">$1.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right">0.0%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Cardano (ADA)</TableCell>
                  <TableCell className="text-right">$2.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-0.3%</TableCell>
                </TableRow>                <TableRow>
                  <TableCell className="font-medium">Ethereum (ETH)</TableCell>
                  <TableCell className="text-right">$3,000.00</TableCell>
                  <TableCell className="text-right">$350 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-1.3%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Binance Coin (BNB)</TableCell>
                  <TableCell className="text-right">$500.00</TableCell>
                  <TableCell className="text-right">$75 Billion</TableCell>
                  <TableCell className="text-right text-green-500">+0.7%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Tether (USDT)</TableCell>
                  <TableCell className="text-right">$1.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right">0.0%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Cardano (ADA)</TableCell>
                  <TableCell className="text-right">$2.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-0.3%</TableCell>
                </TableRow>                <TableRow>
                  <TableCell className="font-medium">Ethereum (ETH)</TableCell>
                  <TableCell className="text-right">$3,000.00</TableCell>
                  <TableCell className="text-right">$350 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-1.3%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Binance Coin (BNB)</TableCell>
                  <TableCell className="text-right">$500.00</TableCell>
                  <TableCell className="text-right">$75 Billion</TableCell>
                  <TableCell className="text-right text-green-500">+0.7%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Tether (USDT)</TableCell>
                  <TableCell className="text-right">$1.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right">0.0%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Cardano (ADA)</TableCell>
                  <TableCell className="text-right">$2.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-0.3%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Ethereum (ETH)</TableCell>
                  <TableCell className="text-right">$3,000.00</TableCell>
                  <TableCell className="text-right">$350 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-1.3%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Binance Coin (BNB)</TableCell>
                  <TableCell className="text-right">$500.00</TableCell>
                  <TableCell className="text-right">$75 Billion</TableCell>
                  <TableCell className="text-right text-green-500">+0.7%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Tether (USDT)</TableCell>
                  <TableCell className="text-right">$1.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right">0.0%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Cardano (ADA)</TableCell>
                  <TableCell className="text-right">$2.00</TableCell>
                  <TableCell className="text-right">$60 Billion</TableCell>
                  <TableCell className="text-right text-red-500">-0.3%</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
